### ISSUE TITLE
Frequent request errors on getInclusionStates()

### ISSUE THREAD

**Issue by cyclux** [SemkoDev/field.cli#28]
There are a lot of request errors while using `getInclusionStates()` on field.carriota.com balancer. Like 25% of the answers are request errors. By far most frequent of them is `One of the tips absents`. Sometimes it is `The subtangle is not solid` or `iri not ready`. I only used `getInclusionStates()` yet, but I guess other requests look similar.
Is this a problem of the individual nodes? If so, is it possible to penalize those nodes, so they do not get chosen by the balancer so often?

**Comment by Pomyk** [comment]
A few non-synced nodes have even top scores.

**Comment by romansemko** [comment]
After the changes to the load balancer two weeks ago, this issue should appear less. The problem comes when a node that processes a transaction sees a tip that it does not know of. I added a check in the load balancer to ignore such responses where possible, returning a correct response from another node.
