### ISSUE TITLE
yarn (ERROR: There are no scenarios; must have at least one.)

### ISSUE THREAD

**Issue by footloosejava** [SemkoDev/field.cli#6]
$ yarn
ERROR: There are no scenarios; must have at least one.

Building locally, please specify correct yarn instructions.

Thanks.

**Comment by footloosejava** [comment]
Bad yarn install. Fixed.

**Comment by flarn2006** [comment]
To be more specific, @footloosejava was running an entirely different program that also happens to be called `yarn`. It seems to be somewhat of a common mistake, because when you don't have yarn installed, Ubuntu says you can install it from the apt package `cmdtest`, which actually contains that other, unrelated `yarn`. So people install it without realizing they're instead installing a package completely unrelated to what they need.

Just thought I'd post that in case anyone else has this problem—if you're getting this error when trying to use yarnpkg, that is certainly the problem. Do `apt purge cmdtest` (unless you still need cmdtest for something else) and follow the [installation instructions](https://yarnpkg.com/lang/en/docs/install/) on the yarn website.
